apply plugin: 'application'

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop"
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
    }
    test {
        java {
            srcDirs = []
        }
    }
}

application {
    mainClass = 'ir.sharif.ap.lwjgl3.Lwjgl3Launcher'
}

def assetsDir = rootProject.file('assets')

tasks.named('run') {
    workingDir = assetsDir
    if (System.getProperty('os.name').toLowerCase().contains('mac')) {
        jvmArgs += '-XstartOnFirstThread'
    }
}

jar {
    dependsOn configurations.runtimeClasspath
    archiveFileName = "group-33-${project.version}.jar"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
    from assetsDir
    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA', 'META-INF/*.MF'
}
